<!-- 
Copyright © 2013 The Regents of the University of Michigan
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 
For more information, questions, or permission requests, please contact:
Yongqun “Oliver” He - yongqunh@med.umich.edu
Unit for Laboratory Animal Medicine, Center for Computational Medicine & Bioinformatics
University of Michigan, Ann Arbor, MI 48109, USA
He Group:  http://www.hegroup.org
-->
<!--
Author: Yongqun 'Oliver' He, Zuoshuang Xiang
The University Of Michigan
He Group
Date: June 2008 - December 2013
Purpose: F & Q page of Ontobee.
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><!-- InstanceBegin template="/Templates/default.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Ontobee</title>
<!-- InstanceEndEditable --><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="shortcut icon" href="/favicon.ico" />
<link href="css/styleMain.css" rel="stylesheet" type="text/css">
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4869243-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
<div id="topbanner"><a href="/index.php" style="font-size:36px; color:#111144; text-decoration:none"><img src="images/logo.gif" alt="Logo" width="280" height="49" border="0"></a></div>
<div id="topnav"><a href="index.php" class="topnav">Home</a><a href="introduction.php" class="topnav">Introduction</a><a href="ontostat/index.php" class="topnav">Statistics</a><a href="sparql/index.php" class="topnav">SPARQL</a><a href="ontobeep/index.php" class="topnav">Ontobeep</a><a href="tutorial/index.php" class="topnav">Tutorial</a><a href="faqs.php" class="topnav">FAQs</a><a href="references.php" class="topnav">References</a><a href="links.php" class="topnav">Links</a><a href="contactus.php" class="topnav">Contact</a><a href="acknowledge.php" class="topnav">Acknowledge</a><a href="news.php" class="topnav">News</a></div>
<div id="mainbody">
<!-- InstanceBeginEditable name="Main" -->
<h3 class="head3_darkred">Frequently Asked Questions</h3>
<p><strong>1. What is Ontobee? </strong></p>
<p> Ontobee is a  linked dataa server that serves as linked data for dereferencing ontology terms. Ontobee has been used as the default onotlogy linked data server for most OBO Foundry library ontologies. The Ontobee program also includes many ontologies that are not  listed in the OBO Foundry library. </p>
<p><strong>2. How are the ontologies stored and queried in Ontobee? </strong></p>
<p> The  ontologies listed in Ontobee are primarily retrieved from the OBO Foundry library. Ontobee also maintains a small number of other ontologies based on needs and requests. These ontologies are processed into RDF triples and  then uploaded to the Hegroup Virtuoso RDF triple store. Upon a user's query request, Ontobee then executes SPARQL query scripts to query the results from the RDF triple store, process the results, and present the results in RDF format as the source and in HTML format to a web browser. </p>
<p><strong>3. What is the main feature of Ontobee? </strong></p>
<p>Based on the XSLT and SPARQL technologies, Ontobee achieves the following feature: for each ontology term, Ontobee  returns a source page in the RDF format, which supports the Semantic Web and Linked (Open) Data applications. In addition, Ontobee acts as a web-based browser of the ontology term information in HTML format. Ontobee provides query and visualization of ontology terms and ontology hierarchy. </p>
<p><strong>4. What are the differences between the HTML page and the RDF source file for each ontology term, both generated by Ontobee? </strong></p>
<p>This OWL (RDF/XML) format is the default page format for the term URI. The HTML file is embedded in a XSL stylesheet introduced in the beginning of  the OWL file. When the term URI was visited by using a web browser, both the OWL file and the HTML content will be retrieved but only the HTML content will be shown in the browser for easy reading. A user can easily access the OWL (RDF/XML) content by check the source code of the  web page for an ontology term. Alternatively, the OWL output file can be retrieved by a web application program, or a Semantic Web system. This approach does not need a human visit to the HTML web page. </p>
<p><strong>5. What are the design principles of the Ontobee program?</strong></p>
<p>Ontobee has been developed by following specific design principles. Some specific requirements we are aiming to address with Ontobee are:</p>
<ul>
  <li> Document and provide a consistent response for each OBO Library ontology.</li>
  <li> Linked Data Browsing</li>
  <li>Per term RDF-XML is valid OWL-DL.</li>
  <li> Includes an import of the full ontology, so the term is clearly defined. LOD browsers can choose whether or not to pay attention to the import.</li>
  <li>All necessary labels included.</li>
  <li> Attribution given, when available.</li>
  <li>No content negotiation - content negotiation confuses the identity of the resource. We prefer different URIs for different encodings.</li>
  <li>Conformance to httpRange-14 or chosen successor.</li>
  <li> Display of ontology developer html in addition, where developers have page-per-term resources.</li>
  <li> Links to or inclusion of additional html material.<br>
  </li>
</ul>
<p>It is noted that this list of requirements is  being revisited and updated. </p>
<p><strong>6. What is Ontobeep? </strong></p>
<p> Ontobeep is an ontology alignment and comparison program that is developed based on the basic Ontobee function of serving and browsing linked data for ontology terms. Ontobeep retrieves selected ontologies using SPARQL and display them in a single ontological hierarchy structure. The terms are labeled with following parentheses with the names of specified ontologies that contain these terms. Shared and unique ontology terms among different ontologies are also calculated. A statistics page is also provided for users to take a careful review. </p>
<p><strong>7. In some rare case, my Firefox was crashed when I clicked some ontology term in Ontobee? </strong></p>
<p>This scenario typically does not happen. If it occurs, it  most likely occurs when this page is too large with various reasons. We are seeking ways to solve this problem. It does not occur in Internet Explorer. So if it happens, you can try to use Internet Explorer. If it still happens, please let us know. </p>
<p><strong>8. How can I contact the Ontobee development team to  make requests or ask questions?  </strong></p>
<p>Please refer to the <a href="contactus.php">Contact Us</a> page for information about contact. </p>
<p>&nbsp;</p>
<!-- InstanceEndEditable -->
</div>
<div id="footer">
  <div id="footer_hl"></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td><div id="footer_left"><a href="http://www.hegroup.org" target="_blank">He Group</a><br>
University of Michigan Medical School<br>
Ann Arbor, MI 48109</div></td>
		<td width="300"><div id="footer_right"><a href="http://www.umich.edu" target="_blank"><img src="images/wordmark_m_web.jpg" alt="UM Logo" width="166" height="20" border="0"></a></div></td>
	</tr>
</table>
</div>
</body>
<!-- InstanceEnd --></html>
