<!-- 
Copyright © 2013 The Regents of the University of Michigan
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
 
http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 
For more information, questions, or permission requests, please contact:
Yongqun “Oliver” He - yongqunh@med.umich.edu
Unit for Laboratory Animal Medicine, Center for Computational Medicine & Bioinformatics
University of Michigan, Ann Arbor, MI 48109, USA
He Group:  http://www.hegroup.org
-->
<!--
Author: Yongqun Oliver He, Zuoshuang Xiang
The University Of Michigan
He Group
Date: June 2008 - December 2013
Purpose: News page of Ontobee.
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><!-- InstanceBegin template="/Templates/default.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Ontobee</title>
<!-- InstanceEndEditable --><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="shortcut icon" href="/favicon.ico" />
<link href="css/styleMain.css" rel="stylesheet" type="text/css">
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4869243-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>

<body>
<div id="topbanner"><a href="/index.php" style="font-size:36px; color:#111144; text-decoration:none"><img src="images/logo.gif" alt="Logo" width="280" height="49" border="0"></a></div>
<div id="topnav"><a href="index.php" class="topnav">Home</a><a href="introduction.php" class="topnav">Introduction</a><a href="ontostat/index.php" class="topnav">Statistics</a><a href="sparql/index.php" class="topnav">SPARQL</a><a href="ontobeep/index.php" class="topnav">Ontobeep</a><a href="tutorial/index.php" class="topnav">Tutorial</a><a href="faqs.php" class="topnav">FAQs</a><a href="references.php" class="topnav">References</a><a href="links.php" class="topnav">Links</a><a href="contactus.php" class="topnav">Contact</a><a href="acknowledge.php" class="topnav">Acknowledge</a><a href="news.php" class="topnav">News</a></div>
<div id="mainbody">
<!-- InstanceBeginEditable name="Main" -->
<h3 class="head3_darkred">News</h3>
<p>The Ontobee program was originally developed as a web browser for the Vaccine Ontology (VO) in He Group.  The name &quot;OntoBee&quot; (later changed to &quot;Ontobee&quot;) was given in  2009. The website domain name ontobee.org was registered by Oliver in 2010. The development and improvement of Ontobee have benefited a lot from   many suggestions, comments, and discussions from the community. Thank you! </p>
<p><strong>Here we have collected  a list of news related to Ontobee: </strong></p>
<ul>
  <li><strong>10/11/2013:</strong> Several improvements were made by Bin on the Ontobee statistics proejct. A new <a href="ontostat/index.php">statistics coverpage</a> was also generated and shown on the Ontobee navigation bar. </li>
  <li><strong>9/30/2013</strong>: Mr. Bin Zhao in He lab developed an ontology statistics page for each ontology. An example is shown <a href="http://www.ontobee.org/ontostat.php?ontology=ICO">HERE</a> (for Informed Consent Ontology or ICO). This page can be linked by clicking on &quot;Detailed Statistics&quot; on the ontology home page such as the <a href="http://www.ontobee.org/browser/index.php?o=ICO">ICO webpage</a>. The program was made openly available on 9/30/2013. </li>
  <li><strong>8/29-9/1/2013</strong>: Ontologies and ontology terms in Ontobee could not be dereferenced. The reason is the broken Virtuoso RDF server. Oliver tried to resume the ontology RDF triiple store. However, the triple store was not stable and easily broken again. On 8/31, Yue helped to update and install the Virtuoso version 6.1.7. However, some compatibility issue occurred. New efforts will be put to ensure a smooth update to new Virtuoso version. Anyway, the RDF triple store database appeared back and stable for now. The daily RDF triple store update feature was temporarily closed. </li>
  <li><strong>8/22/2013:</strong> The Ontobee <a href="tutorial/tutorial_sparql.php">SPARQL tutorial </a>web page was generated by Bin Zhao and Olvier. </li>
  <li><strong>8/18/2013:</strong> The Ontobee development <a href="history.php">History</a> web page was generated and posted by Oliver. </li>
  <li><strong>8/14/2013:</strong> Oliver started to fill up information on the Ontobee <a href="tutorial/index.php">tutorial web page.</a> </li>
  <li>8/10/2013: A bug related to a special character handling was solved with Yue Liu's help. </li>
  <li><strong>8/2/2013:</strong> The <a href="https://groups.google.com/forum/#!forum/ontobee-discuss">Ontobee-discuss Google Group</a> was generated by Oliver. </li>
  <li><strong>7/29-30/2013:</strong> Ontobee was broken due to a broken RDF triple store. Oliver restarted the Virtuoso triple store and reloaded the OWL updated program., </li>
  <li><strong>7/7/2013:</strong> In the <a href="http://ncorwiki.buffalo.edu/index.php/2013_ICBO_OBO_tutorial">ICBO 2013 OBO Foundry tutorial session</a>, Jie Zheng and others presented and discussed Ontobee and related technologies (including OntoFox). Both Ontobee and OntoFox use the same Hegroup RDF triple store. When the RDF triple store is broken, both Ontobee and OntoFox won't work properly. </li>
  <li><strong>March 22, 2013</strong>: The last day of Allen's working in He lab. Oliver started to take the responsibility of maintaining, debugging, and updating Ontobee. Allen agreed to provide necessary consultation if needed. </li>
  <li><strong>Summer 2011 to 2013: </strong>Incremental improvements (including debugging) of Ontobee. The further Ontobee development during this period was  motivated by many requests from the community.  </li>
  <li><strong>Summer, 2011: </strong>Ontobee started to use <a href="http://sparql.hegroup.org/sparql/">Hegroup RDF triple store</a> to get all OWL files. Since Aug 2010, Ontobee had partially used Neurocommons RDF triple store. However, the Neurocommons RDF triple store  was not continuously maintained and updated. In addition, this Neurocommon triple store used unmerged ontologies, which led to the ignorance of all imports when the base ontology was queried from the triple store. Therefore, the usage of the unmerged version made  the data incomplete (i.e., the imported data missing from the base ontology) and slower query performance. </li>
  <li><strong>July, 2011</strong>: Oliver attended the 2nd ICBO meeting and presented the Ontobee work. The <a href="http://www.ontobee.org/Ontobee_ICBO-2011_Proceeding.pdf">first Ontobee paper</a> was also accepted for publication. As shown in the paper, the name &quot;OntoBee&quot; has been changed to &quot;Ontobee&quot;. </li>
  <li><strong>Dec 9, 2010: </strong>Allen presented Ontobeep, an extension and application of OntoBee, and used Ontobeep to study the IDO extensions in  the<a href="http://www.bioontology.org/wiki/index.php/IDO_Workshop_2010"> IDO Workshop 2010</a> at Baltimore Airport Hilton, Baltimore, MD, USA. The Ontobeep idea came from Oliver, and the Ontobeep program was co-developed by Allen and Oliver. See Allen's  presentation <a href="http://ontology.buffalo.edu/10/IDO/xiang.pptx">PPT file located in the IDO workshop</a> or the <a href="docs/20101208IDO.pdf">PDF  file located in Ontobee</a> server. </li>
  <li><strong>Aug-Dec, 2010:</strong> All OBI PURLs resolved to Ontobee. </li>
  <li><strong>Aug 26, 2010:</strong> Bjoern Peters  would like to link directly from an OBI ID to a corresponding website with definition, metadata, synonyms etc. Oliver He suggested to Bjoern that Ontobee could be used for dereferencing OBI ontology term IDs. Such a feature had been implemented for VO already at that time. Oliver further mentioned the unique feature of Ontobee that Ontobee &quot;managed to separate the web display and source OWL file output &quot; with one http: URL. What a user input an ontology VO term IRI, the use can find the HTM information from the Ontobee web site. However, if you look for the source of the web page, it's owl format and contains all information about this term. The automatical deferencing of OBI terms in Ontobee was not ready for OBI terms yet. One reason was that the forwarding system (from OBO PURLS to Ontobee) was not established. Chris Mungall  proposed to use OntoBee for all OBO foundry ontology term visualization. He group was working with Chris Mungell and Alan Ruttenberg to get more features available. Check the <a href="http://obi-developers.2851539.n2.nabble.com/linking-OBI-IDs-to-website-entry-td5467522.html#a5467598">email thread</a>. </li>
  <li><strong>May 18, 2010</strong>: Oliver registered the web domain name: ontobee.org. </li>
  <li><strong>Fall 2009 to early 2010</strong>: Allen was able to update his script to generate RDF/XML source code, which included a XSL link to the HTML document. The contents of the RDF and HTML documents are different. From any HTML page, if the source of the web page is checked, it's owl format and contains all information about this term. So we have managed to separate the web display and source OWL file output. This feature supports semantic web application. </li>
  <li><strong>Oct 05, 2009</strong>: Melanie Courtot recommended VOBrowser (i.e., OntoBee) to the OBI group. With Oliver's supervision and support, Allen Xiang from He Laboratory started to extend the OntoBee method for OBI. Check the <a href="http://obi-developers.2851539.n2.nabble.com/OBI-browser-and-SVN-access-td3770617.html">email thread</a>. </li>
  <li><strong>September, 2009</strong>: The name &quot;OntoBee&quot; was coined by Oliver He, and the OntoBee project was set up with the URL: http://ontobee.hegroup.org/. This system stored an ontology (or ontologies) in a Virtuoso RDF database, and then used PHP and   SPARQL programming to access the rdf database and make sparql queries.   The tool&nbsp;could not    support SOAP.</li>
  <li><strong>July, 2008:</strong> The VO Browser (the early version of Ontobee) was launched in the <a href="http://www.violinet.org">VIOLIN</a> <a href="http://www.violinet.org/vaccineontology">Vaccine Ontology (VO)</a> website. Note: The old VO Browser URL (http://www.violinet.org/vaccineontology/vobrowser) was discontinued later and replaced by: <a href="http://www.ontobee.org/browser/index.php?o=VO">http://www.ontobee.org/browser/index.php?o=VO</a>.</li>
  </ul>
<p>&nbsp;</p>
<p><strong>Notes:</strong></p>
<ul>
  <li>Link to OBI developers'  discussion emails that are related to Ontobee: <a href="http://obi-developers.2851539.n2.nabble.com/template/NamlServlet.jtp?macro=search_page&node=2851539&query=OntoBee">http://obi-developers.2851539.n2.nabble.com/template/NamlServlet.jtp?macro=search_page&amp;node=2851539&amp;query=OntoBee</a></li>
  <li>Search Google for &quot;Ontobee ontology&quot;: <a href="https://www.google.com/search?q=Ontobee+ontology">https://www.google.com/search?q=Ontobee+ontology</a></li>
  <li>Search Google Scholar for  &quot;Ontobee ontology&quot;:<a href="http://scholar.google.com/scholar?hl=en&q=Ontobee+ontology"> http://scholar.google.com/scholar?hl=en&amp;q=Ontobee+ontology</a></li>
  <li>See more acknowledgements on Ontobee development from the <a href="acknowledge.php">Acknowledgements</a> web page. </li>
  <li>Know more information about the  <a href="history.php">History of Ontobee Development</a>. </li>
</ul>
<p>&nbsp;</p>
<!-- InstanceEndEditable -->
</div>
<div id="footer">
  <div id="footer_hl"></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td><div id="footer_left"><a href="http://www.hegroup.org" target="_blank">He Group</a><br>
University of Michigan Medical School<br>
Ann Arbor, MI 48109</div></td>
		<td width="300"><div id="footer_right"><a href="http://www.umich.edu" target="_blank"><img src="images/wordmark_m_web.jpg" alt="UM Logo" width="166" height="20" border="0"></a></div></td>
	</tr>
</table>
</div>
</body>
<!-- InstanceEnd --></html>
