<?php

/**
 * Copyright © 2015 The Regents of the University of Michigan
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 * 
 * For more information, questions, or permission requests, please contact:
 * Yongqun “Oliver” He - yongqunh@med.umich.edu
 * Unit for Laboratory Animal Medicine, Center for Computational Medicine & Bioinformatics
 * University of Michigan, Ann Arbor, MI 48109, USA
 * He Group:  http://www.hegroup.org
 */

/**
 * @file acknowledge.php
 * @author Yongqun Oliver He
 * @author Zuoshuang Allen Xiang
 * @author Edison Ong
 * @since Sep 3, 2015
 * @comment 
 */
 
if (!$this) {
	exit(header('HTTP/1.0 403 Forbidden'));
}

?>

<?php require TEMPLATE . 'header.default.dwt.php'; ?>

<h3 class="head3_darkred">Acknowledgements</h3>
<p> The Ontobee software system has primarily been developed by <a href="http://www.hegroup.org/">He Group</a>, particularly <a href="https://www.linkedin.com/pub/zuoshuang-allen-xiang/1b/797/90b">Allen Xiang</a> and <a href="http://www.hegroup.org/aboutUs/Oliver.html">Oliver He</a>, at the University of Michigan Medical School, which was supported by  NIH-NIAID grant R01AI081062 (funded to Oliver He). The He Group has developed all the code of the Ontobee software (including Ontobeep). </p>
<p>Ontobee was originated from the development of a Vaccine Ontology (VO) Browser by Allen and Oliver during the period of July 2008 - fall 2009. Using PHP and Virtuoso SPARQL technologies, the VO browser was capable of <strong><em>dynamically dereferencing individual ontology term URIs to indivudal HTML pages</em></strong>. The HTML visualization styles out of the VOBrowser program can be seen from two screenshots generated by the program: (i) <a href="docs/VOBrowser-screenshot-ASM-May2009.png">Screenshot #1</a> generated  for an ASM poster presentation in May 2009; (ii) ) <a href="docs/VOBrowser-screenshot-July2009.png">Screenshot #2</a> generated for another <a href="http://precedings.nature.com/documents/3552/version/1">poster presentation</a> in ICBO-2009 conference held in July 2009.   </p>
<p>Allen and Oliver applied the same technology to generate an Ontology for Biomediccal Investigations (<a href="http://obi-ontology.org/">OBI</a>) browser and announced it on Oct 2, 2009. OBI developers <a href="https://www.linkedin.com/in/mcourtot">Melanie Courtot</a> and <a href="https://www.linkedin.com/profile/view?id=27312566">James Malone</a> (among others) suggested the addition of dereferencing ontology terms to RDF. By Oct 22, 2009, inspired by  an xslt-based prototype published by (<a href="http://webont.org/owled/2008/papers/owled2008eu_submission_38.pdf">Courtot et al, 2008</a>), Allen and Oliver updated Ontobee to achieve the feature of <strong><em>dynamically dereferencing individual ontology term URIs to indivudal RDF pages</em></strong> . This success marks the first achievement  of the two key features of Ontobee, <em>i.e.</em>, dynamically dereferencing individual ontology term URIs to both HTML and RDF pages using SPARQL, XSLT and other technologies. </p>
<p>Allen was the primary Ontobee code programmer  before he left Oliver He lab in March 2013. Oliver was responsible for coding most HTML text in Ontobee before Allen left. They co-designed the VO browser and the early versions of Ontobee (note: it was once named &quot;Ontobrowser&quot; or &quot;OntoBee&quot;). After the early successes by the end of 2009, Ontobee was further developed to meet the needs of VO and OBI use cases and suggestions/requests from the wide ontology community. Both Allen and Oliver were very responsive and usually acted very fast to accomplish various requests and suggestions from the community. These resulted in further  improvements and success of the program.  </p>
<p>The next key feature  of Ontobee to acknowledge is <em><strong>the usage of Ontobee as the default linked ontology data server for OBO Foundry library ontologies</strong></em>. Ontobee was first used to resolve VO PURLs (see <a href="http://obi-developers.2851539.n2.nabble.com/linking-OBI-IDs-to-website-entry-td5467522.html">email thread</a>), then OBI PURLs.  By the end of 2010, all OBI ontology term PURL IDs were resolved to Ontobee by default. The OBO PURL  redirection protocol was later  described in the document &quot;<a href="https://code.google.com/p/obo-foundry-operations-committee/wiki/OBOPURLDomain">OBOPURLDomain</a>&quot; prepared and maintained by the <a href="https://code.google.com/p/obo-foundry-operations-committee/">OBO Foundry Operation Committee</a>. Many OBI and OBO Foundry members, especially Alan Ruttenberg, Chris Mungall, and Melanie Courtot, have contributed a lot to achieving this goal. They have also provided many  suggestions, guidance,  and discussions in different areas of Ontobee development.</p>
<p><a href="https://www.linkedin.com/in/alanruttenberg">Alan Ruttenberg</a>  has contributed a lot to the  further development of Ontobee. The Ontobee addition of deferencing ontology URIs to RDF  was inspired by the prototype originally developed by Alan and Melanie among others. For a period of time, Ontobee interacted via SPARQL with the NeuroCommons RDF triple store (in addition to the Hegroup RDF triple store) to query  the information of many OBO ontologies.  The NeuroCommons RDF triple store was developed by Alan and its colleagues. Alan provided guidance to Allen on how to efficiently query RDF triple store and improve the performance. Alan also contributed  to the design of improved  layout and contents of Ontobee HTML and RDF content pages.</p>
<p><a href="http://berkeleybop.org/person/chris-mungall">Chris Mungall</a> suggested and contributed significantly to the usage of Ontobee as the default OBO linked ontology data server. He set up and maintained   the OBO foundry ontology PURLS and the OBO foundry ontology setting file that has been used by Ontobee to automatically retrieve and syncronize with OBO foundry ontologies.  Chris  frequently provided suggestions and comments. </p>
<p>Melanie Courtot recommended Ontobee to OBI group on Oct 05, 2009 (Check related <a href="http://obi-developers.2851539.n2.nabble.com/OBI-browser-and-SVN-access-td3770617.html">email thread</a>). Melanie  has also provided valuable discussions, comments, and suggestions.</p>
<p>Oliver and Allen independently developed <a href="ontobeep/index.php"><strong>Ontobeep</strong></a>, an  Ontobee-based program  used for  ontology alignment, comparison, and analysis. Allen first presented Ontobeep in <a href="http://www.bioontology.org/wiki/index.php/IDO_Workshop_2010">IDO Workshop 2010</a> held on Dec 8-9, 2010. </p>
<p>Since Allen left the He lab in March 2013, Oliver has taken the full responsibility for Ontobee maintenance, debugging, and updating. Later Oliver got much help from Mrs. Yue Liu and Bin Zhao: <br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Mr. <a href="https://www.linkedin.com/profile/view?id=25884919">Yue Liu</a>, an experienced software developer in the University of Michigan, has volunteered starting summer 2013 to help support the Ontobee software debugging and maintenance. <br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Mr. <a href="https://www.linkedin.com/profile/view?id=203083851">Bin Zhao</a>, a graduate student in the School of Information inthe University of Michigan, spent part time to work with Oliver on  generating the Ontobee SPARQL tutorial web page in August 2013. This work was supported by a University of Michigan MCubed project funded to Oliver and two other PIs in the university.  Since September 1, 2013, Oliver used his NIH R01 grant and internal bridging fund to hire Bin as a part-time research assistant. Bin was the primary developer of Ontobee Statistics program (later named <a href="ontostat/index.php"><strong>Ontobeest</strong></a>). </p>
<p>We also like to thank <span id="internal-source-marker_0.13648349562720385"><a href="http://ontolog.cim3.net/cgi-bin/wiki.pl?JieZheng">Jie Zheng</a>, <a href="http://james.overton.ca/">James A. Overton</a>, <a href="http://www.liai.org/pages/faculty-peters">Bjoern Peters</a>, <a href="https://www.linkedin.com/pub/melissa-haendel/2/723/bb9">Melissa Haendel</a>, <a href="https://www.linkedin.com/pub/jonathan-rees/0/332/aa4">Jonathan Rees</a>, Maryanne Martone, <a href="http://www.oerc.ox.ac.uk/people/philippe-rocca-serra">Philippe Rocca-Serra</a>, <a href="http://www.ebi.ac.uk/about/people/helen-parkinson">Helen Parkinson</a>, <a href="http://ontology.buffalo.edu/smith/">Barry Smith</a>, and many others, for their valueable comments,  suggestions, and encouragements. </span> We appreciate the strong support from the OBI developers and the OBO Foundry. In addition, we  appreciate all the engagement and support from many researchers and experts from non-OBO Foundry groups and communities.  </p>
<p>The Ontobee development  has also been inspired by many previous and existing works and published references from all over the world.</p>
<p>We would also like to thank all Ontobee users for using Ontobee! Your usage makes Ontobee popular. Thank you! </p>
<p><strong>Notes: </strong></p>
<ul>
  <li>The  Ontobee <a href="history.php"><strong>History</strong></a> page  introduces more detailed history of the  Ontobee development. </li>
  <li>The Ontobee <a href="news.php">News</a> provides information about some time points or milestones in the history of Ontobee development.</li>
  <li>The Ontobee <a href="references.php">References</a> provided a list of references for the Ontobee development and applications.</li>
  <li>This Acknowledgement page was updated by Oliver on March 29 - April 6, 2014. </li>
  </ul>
<br/>

<?php require TEMPLATE . 'footer.default.dwt.php'; ?>